info:
  name: post_device_configurations_from_backuser
  type: http
  seq: 11

http:
  method: POST
  url: "{{base_url}}/api/backuser/device_configurations"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
