info:
  name: post_device_configurations_from_customer
  type: http
  seq: 8

http:
  method: POST
  url: "{{base_url}}/api/customer/device_configurations"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
