info:
  name: delete_device_config
  type: http
  seq: 5

http:
  method: DELETE
  url: "{{base_url}}/api/device/configuration"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
